var DETAIL_CONFIG = {
  LANDLORD_NEW_CODE: 'WxAppfdlxCode',
  FROM_TYPE_SHARE_HOUSE_CODE: 'WxApptjfyCode',
  FROM_TYPE_LANDLORD_NEW: 1,
  FROM_TYPE_SHARE_PUBLIC: 2,
  FROM_TYPE_SHARE_HOUSE: 3,
  FROM_LANDLORD_PACKGET: 4,
  FROM_PC_HOUSE_DETAIL_QR: 5
};
export default DETAIL_CONFIG;