import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children: React.ReactNode,
  team: React.ReactNode,
  analytics: React.ReactNode,
  auth: React.ReactNode
}) {
  console.log(props.analytics);
  const isLogin = true
  return (
    <html lang="en">
      <body className={inter.className}>

        {props.children}
        {/* {props.analytics} */}
        {/* { isLogin ? props.team : props.auth} */}
      </body>
    </html>
  )
}
